name: nodejs-ci

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      # Force git to use https instead of SSH while fetching packages
      # https://github.com/actions/setup-node/issues/214#issuecomment-810829250
      - name: Reconfigure git to use HTTPS authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Install Dependencies
        run: npm ci

      - name: Install RPM package
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install rpm

      - name: Build
        run: npm run dist:ci

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: |
            dist/*.zip
            dist/*.dmg
            dist/*.dmg.blockmap

            dist/*.deb
            dist/*.snap
            dist/*.rpm
            dist/*.AppImage

            dist/*.exe
            dist/*.exe.blockmap

            dist/latest*.yml

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ubuntu-node-14-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
